<?php

namespace lucio\Core\Proxies\__CG__\Lucio\Core\model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Venta extends \Lucio\Core\model\Venta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'fecha', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'cliente', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'cliente1', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'cliente2', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'monto', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoPagadoCliente', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoPagadoCliente1', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoPagadoCliente2', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoDebe', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'ganancia', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoDevolucion', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoActualizado', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'estado', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'observaciones', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'user', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'detalles', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'devoluciones'];
        }

        return ['__isInitialized__', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'fecha', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'cliente', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'cliente1', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'cliente2', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'monto', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoPagadoCliente', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoPagadoCliente1', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoPagadoCliente2', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoDebe', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'ganancia', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoDevolucion', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'montoActualizado', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'estado', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'observaciones', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'user', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'detalles', '' . "\0" . 'Lucio\\Core\\model\\Venta' . "\0" . 'devoluciones'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Venta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCliente1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente1', []);

        return parent::getCliente1();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente1($cliente1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente1', [$cliente1]);

        return parent::setCliente1($cliente1);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente2', []);

        return parent::getCliente2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente2($cliente2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente2', [$cliente2]);

        return parent::setCliente2($cliente2);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoPagadoCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoPagadoCliente', []);

        return parent::getMontoPagadoCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoPagadoCliente($montoPagadoCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoPagadoCliente', [$montoPagadoCliente]);

        return parent::setMontoPagadoCliente($montoPagadoCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoDebeCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoDebeCliente', []);

        return parent::getMontoDebeCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoDebeCliente($montoDebeCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoDebeCliente', [$montoDebeCliente]);

        return parent::setMontoDebeCliente($montoDebeCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoPagadoCliente1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoPagadoCliente1', []);

        return parent::getMontoPagadoCliente1();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoPagadoCliente1($montoPagadoCliente1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoPagadoCliente1', [$montoPagadoCliente1]);

        return parent::setMontoPagadoCliente1($montoPagadoCliente1);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoDebeCliente1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoDebeCliente1', []);

        return parent::getMontoDebeCliente1();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoDebeCliente1($montoDebeCliente1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoDebeCliente1', [$montoDebeCliente1]);

        return parent::setMontoDebeCliente1($montoDebeCliente1);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoPagadoCliente2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoPagadoCliente2', []);

        return parent::getMontoPagadoCliente2();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoPagadoCliente2($montoPagadoCliente2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoPagadoCliente2', [$montoPagadoCliente2]);

        return parent::setMontoPagadoCliente2($montoPagadoCliente2);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoDebeCliente2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoDebeCliente2', []);

        return parent::getMontoDebeCliente2();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoDebeCliente2($montoDebeCliente2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoDebeCliente2', [$montoDebeCliente2]);

        return parent::setMontoDebeCliente2($montoDebeCliente2);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', []);

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente($cliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', [$cliente]);

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto($monto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoDebe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoDebe', []);

        return parent::getMontoDebe();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoDebe($montoDebe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoDebe', [$montoDebe]);

        return parent::setMontoDebe($montoDebe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function addDetalle(\Lucio\Core\model\DetalleVenta $detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetalle', [$detalle]);

        return parent::addDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function addDevolucion(\Lucio\Core\model\DevolucionVenta $devolucion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDevolucion', [$devolucion]);

        return parent::addDevolucion($devolucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalles', []);

        return parent::getDetalles();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetalles($detalles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetalles', [$detalles]);

        return parent::setDetalles($detalles);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevoluciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevoluciones', []);

        return parent::getDevoluciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevoluciones($devoluciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevoluciones', [$devoluciones]);

        return parent::setDevoluciones($devoluciones);
    }

    /**
     * {@inheritDoc}
     */
    public function podesAnularte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'podesAnularte', []);

        return parent::podesAnularte();
    }

    /**
     * {@inheritDoc}
     */
    public function podesCobrarte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'podesCobrarte', []);

        return parent::podesCobrarte();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoPagado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoPagado', []);

        return parent::getMontoPagado();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoPagado($montoPagado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoPagado', [$montoPagado]);

        return parent::setMontoPagado($montoPagado);
    }

    /**
     * {@inheritDoc}
     */
    public function getGanancia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGanancia', []);

        return parent::getGanancia();
    }

    /**
     * {@inheritDoc}
     */
    public function setGanancia($ganancia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGanancia', [$ganancia]);

        return parent::setGanancia($ganancia);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoDevolucion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoDevolucion', []);

        return parent::getMontoDevolucion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoDevolucion($montoDevolucion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoDevolucion', [$montoDevolucion]);

        return parent::setMontoDevolucion($montoDevolucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoActualizado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoActualizado', []);

        return parent::getMontoActualizado();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoActualizado($montoActualizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoActualizado', [$montoActualizado]);

        return parent::setMontoActualizado($montoActualizado);
    }

    /**
     * {@inheritDoc}
     */
    public function getOid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getOid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOid', []);

        return parent::getOid();
    }

    /**
     * {@inheritDoc}
     */
    public function setOid($oid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOid', [$oid]);

        return parent::setOid($oid);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncrypted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncrypted', []);

        return parent::getEncrypted();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncrypted($encrypted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncrypted', [$encrypted]);

        return parent::setEncrypted($encrypted);
    }

    /**
     * {@inheritDoc}
     */
    public function encrypt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encrypt', []);

        return parent::encrypt();
    }

    /**
     * {@inheritDoc}
     */
    public function decrypt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decrypt', []);

        return parent::decrypt();
    }

    /**
     * {@inheritDoc}
     */
    public function getManagedEntities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManagedEntities', []);

        return parent::getManagedEntities();
    }

}
